port: 8080  # Example value
db:
  url: "jdbc:postgresql://localhost:5432/conduit-db"  # Example value
  user: conduit-user
  password: conduit-password
  driver: "org.postgresql.Driver"
cors:
#  allowedOrigins:
#  allowedMethods:
#  allowedHeaders:
#  allowCredentials: