name: Http4k Backend Tests

on:
  push:
    branches:
      - main
      - master
      - 'renovate/**'
    paths:
      - 'conduit-backend/**'
      - 'build-src/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: test-db
      DB_USER: test-user
      DB_PASSWORD: test-password

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        options: >-
          --health-cmd "pg_isready -U ${DB_USER} -d ${DB_NAME}"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run Database Migrations
      uses: docker://flyway/flyway:latest-alpine
      env:
        FLYWAY_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
        FLYWAY_USER: ${DB_USER}
        FLYWAY_PASSWORD: ${DB_PASSWORD}
        FLYWAY_CLEAN_DISABLED: false
        FLYWAY_LOCATIONS: filesystem:/github/workspace/conduit-backend/db-migration/main,filesystem:/github/workspace/conduit-backend/db-migration/test
      with:
        args: clean migrate

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Backend Tests
      working-directory: conduit-backend
      env:
        DB__URL: jdbc:postgresql://postgres:5432/${DB_NAME}
        DB__USER: ${DB_USER}
        DB__PASSWORD: ${DB_PASSWORD}
      run: |
        ./gradlew check 

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-build-reports
        path: conduit-backend/build/reports/
