name: Http4k Backend Tests

on:
  push:
    paths:
      - 'conduit-backend/**'
      - 'build-src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Backend Tests
      working-directory: conduit-backend
      run: |
        ./gradlew check

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-build-reports
        path: conduit-backend/build/reports/
